# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs  > Tasks

stages:
- stage: devDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo Dev JOB 1 
  - job: job2
    steps:
    - bash: echo Dev JOB 2

- stage: ditDeploy
  dependsOn: devDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo DIT JOB 1 

- stage: qaDeploy
  dependsOn: devDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo QA JOB 1 

- stage: prodDeploy
  dependsOn:
     ditDeploy
     qaDeploy
     devDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo PROD JOB 1 