# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


strategy:
  matrix:
    linux:
      operatingSystem: "ubantu latest"
    macos:
      operatingSystem: "macos latest"
    windows:
      operatingSystem: "windows latest"
pool: 
  vmImage: $(operatingSystem)

# Pipelines > Stages > Jobs  > Tasks

steps:
  - script: echo -Running On $(operatingSystem)
    
